=== lukeautry/tsoa/packages/tsoa/schema.json
{"$ref":"#/definitions/JsonSchema","$schema":"http://json-schema.org/draft-07/schema#","definitions":{"JsonSchema":{"additionalProperties":false,"properties":{"$schema":{"description":"./node_modules/tsoa/schema.json","type":"string"},"compilerOptions":{"additionalProperties":{},"description":"Typescript CompilerOptions to be used during generation","type":"object"},"controllerPathGlobs":{"description":"An array of path globs that point to your route controllers that you would like to have tsoa include.","items":{"type":"string"},"type":"array"},"entryFile":{"description":"The entry point to your API","type":"string"},"ignore":{"description":"Directories to ignore during TypeScript metadata scan","items":{"type":"string"},"type":"array"},"multerOpts":{"$ref":"#/definitions/multer.Options","description":"Multer's options to generate multer's middleware. It doesn't support storage option"},"noImplicitAdditionalProperties":{"description":"Modes that allow you to prevent input data from entering into your API. This will document your decision in the swagger.yaml and it will turn on excess-property validation (at runtime) in your routes.","enum":["throw-on-extras","silently-remove-extras","ignore"],"type":"string"},"routes":{"$ref":"#/definitions/RoutesConfig","description":"Route generation configuration object"},"spec":{"$ref":"#/definitions/SpecConfig","description":"Swagger generation configuration object"}},"required":["entryFile","routes","spec"],"type":"object"},"RoutesConfig":{"additionalProperties":false,"properties":{"authenticationModule":{"description":"Authentication Module for express, hapi and koa","type":"string"},"basePath":{"description":"Base API path; e.g. the '/v1' in https://myapi.com/v1","type":"string"},"esm":{"default":false,"description":"When enabled, the imports in the routes files will have a `.js` extention to support esm.","type":"boolean"},"iocModule":{"description":"IOC module; e.g. './inversify/ioc' where IOC container named `iocContainer` is defined (https://github.com/inversify/InversifyJS)","type":"string"},"middleware":{"description":"Middleware provider.","enum":["express","hapi","koa"],"type":"string"},"middlewareTemplate":{"description":"Override the Middleware template","type":"string"},"noWriteIfUnchanged":{"description":"Avoid writing the generated route file if the existing file is identical (useful to optimize watch processes); false by default","type":"boolean"},"routesDir":{"description":"Routes directory; generated routes.ts (which contains the generated code wiring up routes using middleware of choice) will be dropped here","type":"string"},"routesFileName":{"description":"Routes filename; the filename of the generated route file ('routes.ts' by default)","type":"string"}},"required":["routesDir"],"type":"object"},"SpecConfig":{"additionalProperties":false,"properties":{"basePath":{"description":"Base API path; e.g. the 'v1' in https://myapi.com/v1","type":"string"},"contact":{"additionalProperties":false,"description":"Contact Information","properties":{"email":{"default":"npm package author email","description":"The email address of the contact person/organization.","type":"string"},"name":{"default":"npm package author","description":"The identifying name of the contact person/organization.","type":"string"},"url":{"default":"npm package author url","description":"API Info url The URL pointing to the contact information.","type":"string"}},"type":"object"},"description":{"description":"API description; defaults to npm package description","type":"string"},"host":{"description":"API host, expressTemplate.g. localhost:3000 or myapi.com","type":"string"},"license":{"description":"API license; defaults to npm package license","type":"string"},"name":{"description":"API name; defaults to npm package name","type":"string"},"operationIdTemplate":{"default":"{{titleCase method.name}}","description":"Template string for generating operation ids. This should be a valid handlebars template and is provided with the following context:   - 'controllerName' - String name of controller class.   - 'method' - Tsoa.Method object.","type":"string"},"outputDirectory":{"description":"Generated SwaggerConfig.json will output here","type":"string"},"schemes":{"description":"All communication protocols that your API supports.","items":{"$ref":"#/definitions/Swagger.Protocol"},"type":"array"},"securityDefinitions":{"additionalProperties":{"$ref":"#/definitions/Swagger.Security"},"description":"Security Definitions Object A declaration of the security schemes available to be used in the specification. This does not enforce the security schemes on the operations and only serves to provide the relevant details for each scheme.\n\nYou can use them in your controllers with `@Security(name)` decorator.","type":"object"},"spec":{"description":"Extend generated swagger spec with this object Note that generated properties will always take precedence over what get specified here"},"specFileBaseName":{"default":": \"swagger\"","description":"Base-name of swagger.json or swagger.yaml.","type":"string"},"specMerging":{"default":"immediate","description":"Alter how the spec is merged to generated swagger spec. Possible values:  - 'immediate' is overriding top level elements only thus you can not append a new path or alter an existing value without erasing same level elements.  - 'recursive' proceed to a deep merge and will concat every branches or override or create new values if needed. @see https://www.npmjs.com/package/merge  - 'deepmerge' uses `deepmerge` to merge, which will concat object branches and concat arrays as well @see https://www.npmjs.com/package/deepmerge The default is set to immediate so it is not breaking previous versions.","enum":["immediate","recursive","deepmerge"],"type":"string"},"specVersion":{"$ref":"#/definitions/Swagger.SupportedSpecMajorVersion","description":"Major OpenAPI version to generate; defaults to version 2 when not specified Possible values:  - 2: generates OpenAPI version 2.  - 3: generates OpenAPI version 3."},"tags":{"description":"Swagger Tags Information for your API","items":{"$ref":"#/definitions/Swagger.Tag"},"type":"array"},"termsOfService":{"description":"Link to the page that describes the terms of service. Must be in the URL format.","type":"string"},"useTitleTagsForInlineObjects":{"description":"Sets a title for inline objects for responses and requestBodies This helps to generate more consistent clients","type":"boolean"},"version":{"description":"API version number; defaults to npm package version","type":"string"},"xEnumVarnames":{"default":false,"description":"Enable x-enum-varnames support","type":"boolean"},"yaml":{"description":"If you want to output a YAML version of the spec, set this to true.","type":"boolean"}},"required":["outputDirectory"],"type":"object"},"Swagger.ApiKeySecurity":{"additionalProperties":false,"properties":{"description":{"type":"string"},"in":{"enum":["query","header"],"type":"string"},"name":{"type":"string"},"type":{"const":"apiKey","type":"string"}},"required":["type","name","in"],"type":"object"},"Swagger.BasicSecurity":{"additionalProperties":false,"properties":{"description":{"type":"string"},"type":{"const":"basic","type":"string"}},"required":["type"],"type":"object"},"Swagger.BasicSecurity3":{"additionalProperties":false,"properties":{"description":{"type":"string"},"scheme":{"const":"basic","type":"string"},"type":{"const":"http","type":"string"}},"required":["type","scheme"],"type":"object"},"Swagger.ExternalDocs":{"additionalProperties":false,"properties":{"description":{"type":"string"},"url":{"type":"string"}},"required":["url"],"type":"object"},"Swagger.OAuth2AccessCodeSecurity":{"additionalProperties":false,"properties":{"authorizationUrl":{"type":"string"},"description":{"type":"string"},"flow":{"const":"accessCode","type":"string"},"scopes":{"$ref":"#/definitions/Swagger.OAuthScope"},"tokenUrl":{"type":"string"},"type":{"const":"oauth2","type":"string"}},"required":["type","flow","tokenUrl","authorizationUrl"],"type":"object"},"Swagger.OAuth2ApplicationSecurity":{"additionalProperties":false,"properties":{"description":{"type":"string"},"flow":{"const":"application","type":"string"},"scopes":{"$ref":"#/definitions/Swagger.OAuthScope"},"tokenUrl":{"type":"string"},"type":{"const":"oauth2","type":"string"}},"required":["type","flow","tokenUrl"],"type":"object"},"Swagger.OAuth2ImplicitSecurity":{"additionalProperties":false,"properties":{"authorizationUrl":{"type":"string"},"description":{"type":"string"},"flow":{"const":"implicit","type":"string"},"scopes":{"$ref":"#/definitions/Swagger.OAuthScope"},"type":{"const":"oauth2","type":"string"}},"required":["type","flow","authorizationUrl"],"type":"object"},"Swagger.OAuth2PasswordSecurity":{"additionalProperties":false,"properties":{"description":{"type":"string"},"flow":{"const":"password","type":"string"},"scopes":{"$ref":"#/definitions/Swagger.OAuthScope"},"tokenUrl":{"type":"string"},"type":{"const":"oauth2","type":"string"}},"required":["type","flow","tokenUrl"],"type":"object"},"Swagger.OAuth2Security3":{"additionalProperties":false,"properties":{"description":{"type":"string"},"flows":{"$ref":"#/definitions/Swagger.OAuthFlow"},"type":{"const":"oauth2","type":"string"}},"required":["type","flows"],"type":"object"},"Swagger.OAuth2SecurityFlow3":{"additionalProperties":false,"properties":{"authorizationUrl":{"type":"string"},"description":{"type":"string"},"scopes":{"$ref":"#/definitions/Swagger.OAuthScope"},"tokenUrl":{"type":"string"}},"type":"object"},"Swagger.OAuthFlow":{"additionalProperties":false,"properties":{"authorizationCode":{"$ref":"#/definitions/Swagger.OAuth2SecurityFlow3"},"clientCredentials":{"$ref":"#/definitions/Swagger.OAuth2SecurityFlow3"},"implicit":{"$ref":"#/definitions/Swagger.OAuth2SecurityFlow3"},"password":{"$ref":"#/definitions/Swagger.OAuth2SecurityFlow3"}},"type":"object"},"Swagger.OAuthScope":{"additionalProperties":{"type":"string"},"type":"object"},"Swagger.Protocol":{"enum":["http","https","ws","wss"],"type":"string"},"Swagger.Security":{"anyOf":[{"$ref":"#/definitions/Swagger.BasicSecurity"},{"$ref":"#/definitions/Swagger.BasicSecurity3"},{"$ref":"#/definitions/Swagger.ApiKeySecurity"},{"$ref":"#/definitions/Swagger.OAuth2AccessCodeSecurity"},{"$ref":"#/definitions/Swagger.OAuth2ApplicationSecurity"},{"$ref":"#/definitions/Swagger.OAuth2ImplicitSecurity"},{"$ref":"#/definitions/Swagger.OAuth2PasswordSecurity"},{"$ref":"#/definitions/Swagger.OAuth2Security3"}]},"Swagger.SupportedSpecMajorVersion":{"enum":[2,3],"type":"number"},"Swagger.Tag":{"additionalProperties":false,"properties":{"description":{"type":"string"},"externalDocs":{"$ref":"#/definitions/Swagger.ExternalDocs"},"name":{"type":"string"}},"required":["name"],"type":"object"},"multer.Options":{"additionalProperties":false,"description":"Options for initializing a Multer instance.","properties":{"dest":{"description":"The destination directory for uploaded files. If `storage` is not set and `dest` is, Multer will create a `DiskStorage` instance configured to store files at `dest` with random filenames.\n\nIgnored if `storage` is set.","type":"string"},"limits":{"additionalProperties":false,"description":"An object specifying various limits on incoming data. This object is passed to Busboy directly, and the details of properties can be found at https://github.com/mscdex/busboy#busboy-methods.","properties":{"fieldNameSize":{"description":"Maximum size of each form field name in bytes. (Default: 100)","type":"number"},"fieldSize":{"description":"Maximum size of each form field value in bytes. (Default: 1048576)","type":"number"},"fields":{"description":"Maximum number of non-file form fields. (Default: Infinity)","type":"number"},"fileSize":{"description":"Maximum size of each file in bytes. (Default: Infinity)","type":"number"},"files":{"description":"Maximum number of file fields. (Default: Infinity)","type":"number"},"headerPairs":{"description":"Maximum number of headers. (Default: 2000)","type":"number"},"parts":{"description":"Maximum number of parts (non-file fields + files). (Default: Infinity)","type":"number"}},"type":"object"},"preservePath":{"description":"Preserve the full path of the original filename rather than the basename. (Default: false)","type":"boolean"},"storage":{"$ref":"#/definitions/multer.StorageEngine","description":"A `StorageEngine` responsible for processing files uploaded via Multer. Takes precedence over `dest`."}},"type":"object"},"multer.StorageEngine":{"additionalProperties":false,"description":"Implementations of this interface are responsible for storing files encountered by Multer and returning information on how to access them once stored. Implementations must also provide a method for removing files in the event that an error occurs.","type":"object"}}}

=== lukeautry/tsoa/tests/esm/tsoa.json
{
  "entryFile": "./fixtures/express/server.ts",
  "noImplicitAdditionalProperties": "silently-remove-extras",
  "spec": {
    "outputDirectory": "./dist",
    "host": "localhost:3000",
    "basePath": "/v1",
    "yaml": true,
    "specVersion": 2
  },
  "routes": {
    "basePath": "/v1",
    "routesDir": "./fixtures/express",
    "middleware": "express"
  }
}
